### ISSUE TITLE
Lots of Issues (h5py writing)

### ISSUE THREAD

**Issue by Mblakey** [chennnnnyize/Generative-Molecules#4]
Hi there, there are lots of issues with the h5py read and writing in the preprocessing script, most likely due to updates causing some changes. 

I'm working on fixes however please could you look into the following error 

TypeError: Broadcasting is not supported for complex selections

Caused by line 80 in the preprocess.py script

**Comment by chennnnnyize** [comment]
Hi Michael, thanks for raising this up. Please check this page for some discussions:

https://stackoverflow.com/questions/63076023/h5py-broadcasting-not-supported-when-writing-to-a-complex-selection

I think it is due to version conflicts, but I haven't encountered such issues. Thanks.
